# Loading and testing things on the log files

In [41]:
import numpy as np
import pandas as pd

In [46]:
path = 'insiders/CDE1846-logs.csv'

In [47]:
df = pd.read_csv(path)

In [48]:
df.head()

id           date service_id     user     host  \
0  {E9I0-Y8RU07VC-9190FQRX}  1262590680000      logon  CDE1846  PC-1237   
1  {K1B3-O2GX92AA-9973NEBT}  1262590797000       http  CDE1846  PC-1237   
2  {Z7Q2-D6LZ09NS-1196XQKC}  1262590797000       http  CDE1846  PC-1237   
3  {F6H1-T5BQ19CU-4105ORTK}  1262590991000       http  CDE1846  PC-1237   
4  {F0G7-M7YL37TB-9860TOWI}  1262591636000       http  CDE1846  PC-1237   

                 role  projects  business_unit  \
0  ElectricalEngineer       NaN              1   
1  ElectricalEngineer       NaN              1   
2  ElectricalEngineer       NaN              1   
3  ElectricalEngineer       NaN              1   
4  ElectricalEngineer       NaN              1   

                         functional_unit       department      ...        \
0  2 - ResearchAndEngineering_Commercial  4 - Engineering      ...         
1  2 - ResearchAndEngineering_Commercial  4 - Engineering      ...         
2  2 - ResearchAndEngineering_Commercial  4 - Engineering      ...         
3  2 - ResearchAndEngineering_Commercial  4 - Engineering      ...         
4  2 - ResearchAndEngineering_Commercial  4 - Engineering      ...         

  email_content  file_filename  file_activity file_to_removable_media  \
0           NaN            NaN            NaN                     NaN   
1           NaN            NaN            NaN                     NaN   
2           NaN            NaN            NaN                     NaN   
3           NaN            NaN            NaN                     NaN   
4           NaN            NaN            NaN                     NaN   

  file_from_removable_media file_content  \
0                       NaN          NaN   
1                       NaN          NaN   
2                       NaN          NaN   
3                       NaN          NaN   
4                       NaN          NaN   

                                            http_url http_activity  \
0                                                NaN           NaN   
1  http://photobucket.com/Horses_in_World_War_I/a...     WWW Visit   
2  http://mayoclinic.com/Antonin_Scalia/originali...     WWW Visit   
3  http://photobucket.com/Horses_in_World_War_I/a...     WWW Visit   
4  http://alibaba.com/Cheadle_Hulme/gatley/Punevb...     WWW Visit   

                                        http_content logon_activity  
0                                                NaN          Logon  
1  The series, co-created and co-produced by SCPA...            NaN  
2  He expressed concerns that, given the birds' l...            NaN  
3  The series, co-created and co-produced by SCPA...            NaN  
4  Domitian created two new factions, the Purples...            NaN  

[5 rows x 30 columns]

In [49]:
df.nunique()

id                           37862
date                         37335
service_id                       4
user                             1
host                            10
role                             1
projects                         0
business_unit                    1
functional_unit                  1
department                       1
team                             1
device_file_tree                 0
device_activity                  0
email_to                      1163
email_cc                       402
email_bcc                        2
email_from                     132
email_activity                   2
email_size                    2362
email_attachments              689
email_content                 2394
file_filename                   40
file_activity                    1
file_to_removable_media          1
file_from_removable_media        1
file_content                    38
http_url                       145
http_activity                    1
http_content        

In [55]:
df['email_activity'].unique()

array([nan, 'Send', 'View'], dtype=object)

In [50]:
df['file_filename'].unique()

array([nan, 'C:\\FKXPWMBJ.pdf', 'C:\\W5P5C3ET.pdf',
       'C:\\CDE1846\\UHPBAHJF.pdf', 'C:\\0MARR7W1.doc',
       'C:\\CDE1846\\9PA36MYX.doc', 'C:\\DE2V5QKJ.pdf',
       'C:\\CDE1846\\XZ0H7ZLD.pdf', 'C:\\CDE1846\\XF41FQVS.zip',
       'C:\\CDE1846\\6Z5WZWGU.doc', 'C:\\CDE1846\\CPAWCD4S.doc',
       'C:\\CDE1846\\D6X42ZMS.doc', 'C:\\CDE1846\\2V2HNXLP.doc',
       'C:\\HJDDWGF5.txt', 'C:\\CDE1846\\5YNN4EC1.doc',
       'C:\\33B3fZ4\\T0NO6UHX.doc', 'C:\\75J52H6\\76XFNRMY.doc',
       'C:\\NDW3217\\2ZKN5SSF.txt', 'C:\\71W9187\\U72DKNR8.jpg',
       'C:\\75Tdd11\\89MDWBRP.zip', 'C:\\ANMP7FMC.doc',
       'C:\\52s6447\\1Y371ELW.doc', 'C:\\361Kzq8\\7R4T6PQ4.doc',
       'C:\\IAS0857\\JCNZZ12A.doc', 'C:\\53c5f85\\5FXA20SS.doc',
       'C:\\88LZS71\\2V6UT1DH.doc', 'C:\\8IIIYRYX.zip',
       'C:\\13R4k55\\2RBI4PHU.doc', 'C:\\953Pm49\\2RBI4PHU.doc',
       'C:\\LZDR799P.doc', 'C:\\TKS1549\\2RBI4PHU.doc',
       'C:\\33tR2W2\\206B51GA.doc', 'C:\\KDT1190\\25IN4DT6.zip',
       'C:\\KDT1190\\O8CIUG

In [51]:
df['email_attachments'].unique()

array([nan, 'C:\\KL5P0DHC.txt(1036651)', 'C:\\9C5NYGLS.doc(183535)',
       'C:\\XF35PIFF.doc(1386773)', 'C:\\94F4s85\\2NQ395S7.doc(1031349)',
       'C:\\FH0TKBJW.pdf(192574)', 'C:\\CDE1846\\W5ZX4KBR.jpg(245319)',
       'C:\\23BFcR0\\0NJCKE8D.doc(1202386)',
       'C:\\W0KXSB8L.doc(1289686);C:\\CDE1846\\LQO3FVTN.doc(626013)',
       'C:\\878nvq8\\42WRKIHG.jpg(345756)', 'C:\\NZD74AAO.doc(1199917)',
       'C:\\ZCQ8J0OJ.doc(531244)', 'C:\\CDE1846\\FWBKOUU8.doc(1134363)',
       'C:\\FKXPWMBJ.pdf(1096974);C:\\OYRLB4MU.doc(213856)',
       'C:\\W5P5C3ET.pdf(171373)',
       'C:\\CDE1846\\UHPBAHJF.pdf(1679271);C:\\CDE1846\\JY4BLTSU.doc(734364);C:\\PFQ93AFB.jpg(1763169)',
       'C:\\KL5P0DHC.txt(1036651);C:\\W5P5C3ET.pdf(171373)',
       'C:\\1M5NV2G8.doc(901215)', 'C:\\CDE1846\\JMUTL39G.doc(65099)',
       'C:\\34PZZI7L.jpg(965007);C:\\OOPQ8GJR.doc(1582028);C:\\9QYG59GC.doc(1046415);C:\\CDE1846\\0313HTG3.doc(1432123);C:\\W5P5C3ET.pdf(171373);C:\\CDE1846\\POK0BF2F.pdf(983211);C:\\0MARR7W1

In [52]:
df['host'].unique()

array(['PC-1237', 'PC-7773', 'PC-3933', 'PC-5014', 'PC-2386', 'PC-5128',
       'PC-4738', 'PC-4174', 'PC-8758', 'PC-7271'], dtype=object)

In [53]:
df['email_content'].unique()

array([nan,
       'In 1937, The Times described the half-mile between the railway station and the city (an area including the site of the proposed college) as "something between a refuse heap and a slum"; Nuffield had originally bought the canal basin to beautify that part of the city before he had the idea of building a college to accomplish this. The tower, which would now contain the common room, was moved from the area of the former hall staircase to the east end of the chapel. Little Ring Mountain at the northern end of the field contains at least 70% brown volcanic glass with isolated phenocrysts of plagioclase. This mountain, like others in the area, is considered sacred because it plays an important part of their history.',
       'An Ohio School Facilities Assessment in 2002 reported that it is "very attractive architecturally and merits any means required to preserve it", and that residential units would be the best use. Erich Kunzel, long time Maestro of the Cincinnati Pops

In [54]:
df.shape

(37862, 30)

In [8]:
path = 'safe/BWW1159-logs.csv'

In [9]:
df2 = pd.read_csv(path)

In [10]:
df2.head()

id           date service_id     user     host  \
0  {N4E9-P5QS22FC-0941VOBA}  1262590320000      logon  BWW1159  PC-2798   
1  {F3U1-K1RL06YD-3626EBBX}  1262590397000       http  BWW1159  PC-2798   
2  {B9S5-S8XR31OA-4002IIVS}  1262591003000       http  BWW1159  PC-2798   
3  {W3O0-M4IA41HP-2264EDVS}  1262591154000       http  BWW1159  PC-2798   
4  {Y8B0-L4PV39FP-8028SNNA}  1262591235000       http  BWW1159  PC-2798   

                role  projects  business_unit  \
0  MaterialsEngineer       NaN              1   
1  MaterialsEngineer       NaN              1   
2  MaterialsEngineer       NaN              1   
3  MaterialsEngineer       NaN              1   
4  MaterialsEngineer       NaN              1   

                         functional_unit       department      ...        \
0  2 - ResearchAndEngineering_Commercial  4 - Engineering      ...         
1  2 - ResearchAndEngineering_Commercial  4 - Engineering      ...         
2  2 - ResearchAndEngineering_Commercial  4 - Engineering      ...         
3  2 - ResearchAndEngineering_Commercial  4 - Engineering      ...         
4  2 - ResearchAndEngineering_Commercial  4 - Engineering      ...         

  email_content file_filename file_activity file_to_removable_media  \
0           NaN           NaN           NaN                     NaN   
1           NaN           NaN           NaN                     NaN   
2           NaN           NaN           NaN                     NaN   
3           NaN           NaN           NaN                     NaN   
4           NaN           NaN           NaN                     NaN   

  file_from_removable_media  file_content  \
0                       NaN           NaN   
1                       NaN           NaN   
2                       NaN           NaN   
3                       NaN           NaN   
4                       NaN           NaN   

                                            http_url http_activity  \
0                                                NaN           NaN   
1  http://ilivid.com/Battle_of_Midway/gaido/2009_...     WWW Visit   
2  http://wordpress.org/Marcus_Trescothick/odi/20...     WWW Visit   
3  http://vimeo.com/H_II_region/ionised/2009_Ynzn...     WWW Visit   
4  http://vimeo.com/H_II_region/ionised/2009_Ynzn...     WWW Visit   

                                        http_content logon_activity  
0                                                NaN          Logon  
1  MLS clubs were first included in the U.S. Open...            NaN  
2  Following this public disagreement, D.C. Unite...            NaN  
3  Ticket discounts and special pricing on conces...            NaN  
4  Ticket discounts and special pricing on conces...            NaN  

[5 rows x 30 columns]

In [11]:
df2.nunique()

id                           39572
date                         39226
service_id                       5
user                             1
host                             1
role                             1
projects                         0
business_unit                    1
functional_unit                  1
department                       1
team                             1
device_file_tree                 1
device_activity                  2
email_to                      1314
email_cc                       411
email_bcc                        0
email_from                     211
email_activity                   2
email_size                    2874
email_attachments              659
email_content                 2943
file_filename                  342
file_activity                    4
file_to_removable_media          2
file_from_removable_media        2
file_content                   353
http_url                       283
http_activity                    1
http_content        

In [12]:
df2['device_file_tree'].unique()

array([nan, 'R:\\;R:\\789yK69;R:\\BWW1159'], dtype=object)

In [13]:
df2.count()

id                           39572
date                         39572
service_id                   39572
user                         39572
host                         39572
role                         39572
projects                         0
business_unit                39572
functional_unit              39572
department                   39572
team                         39572
device_file_tree               412
device_activity                822
email_to                      3143
email_cc                      1290
email_bcc                        0
email_from                    3143
email_activity                3143
email_size                    3143
email_attachments              842
email_content                 3143
file_filename                  789
file_activity                  789
file_to_removable_media        789
file_from_removable_media      789
file_content                   789
http_url                     33820
http_activity                33820
http_content        

In [14]:
df2['email_activity'].unique()

array([nan, 'Send', 'View'], dtype=object)

In [15]:
df2['file_activity'].unique()

array([nan, 'File Open', 'File Copy', 'File Delete', 'File Write'],
      dtype=object)

In [16]:
df2['device_activity'].unique()

array([nan, 'Connect', 'Disconnect'], dtype=object)

In [17]:
df2['http_activity'].unique()

array([nan, 'WWW Visit'], dtype=object)

In [18]:
df2['logon_activity'].unique()

array(['Logon', nan, 'Logoff'], dtype=object)

In [19]:
df2.iloc[:, 13:].count().sum()

124250

In [20]:
# the different type of events happening on a host
df2[['email_activity', 'file_activity', 'http_activity', 'logon_activity', 'device_activity']].count().sum() == df2['id'].count()

True

In [21]:
df2['email_to'].unique()

array([nan,
       'Benjamin.Zeph.Holland@dtaa.com;Rhiannon.Uta.Buckley@dtaa.com',
       'Blair.Warren.Woods@dtaa.com', ...,
       'Ferdinand.Colt.Young@dtaa.com;Kelly.Nichole.Madden@dtaa.com;Blair.Warren.Woods@dtaa.com;Colorado.Hamish.Benjamin@dtaa.com',
       'Jeanette.Holder@msn.com',
       'Eagan.Kane.Cervantes@dtaa.com;Benjamin.Zeph.Holland@dtaa.com;Blair.Warren.Woods@dtaa.com'],
      dtype=object)